// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfApq_WN29xxb-kIiuKablzfoq9owFyE',
    appId: '1:943041985172:web:dbd7f171ab271322779281',
    messagingSenderId: '943041985172',
    projectId: 'instagram-7579b',
    authDomain: 'instagram-7579b.firebaseapp.com',
    storageBucket: 'instagram-7579b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX9O5oEThNHEJbuvZxEo8OpoizdRcLuQw',
    appId: '1:943041985172:android:64647150405bbf02779281',
    messagingSenderId: '943041985172',
    projectId: 'instagram-7579b',
    storageBucket: 'instagram-7579b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwlil7q9U4g62RDqQ_p7TmZZACVdfEAd4',
    appId: '1:943041985172:ios:b122f5124515f1b9779281',
    messagingSenderId: '943041985172',
    projectId: 'instagram-7579b',
    storageBucket: 'instagram-7579b.appspot.com',
    iosClientId: '943041985172-ib47msrg3p7t3r8cmh8d7q4h7mh874u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaSMApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwlil7q9U4g62RDqQ_p7TmZZACVdfEAd4',
    appId: '1:943041985172:ios:b122f5124515f1b9779281',
    messagingSenderId: '943041985172',
    projectId: 'instagram-7579b',
    storageBucket: 'instagram-7579b.appspot.com',
    iosClientId: '943041985172-ib47msrg3p7t3r8cmh8d7q4h7mh874u9.apps.googleusercontent.com',
    iosBundleId: 'com.example.instaSMApp',
  );
}
